### ISSUE TITLE
some bug

### ISSUE THREAD

**Issue by linrunzheng** [deepexi-com/replacer-cli#9]
1. 变量如果是运行时的话，需要加上 \"${VALUE}\" 去进行标注
2. 如果组件或者其他地方用到 `process.env` 变量，会变异成一个对象，这时候会出现 bug

**Comment by linrunzheng** [comment]
1. defineEnvs会将代码注入到src里面去，导致报错

**Comment by linrunzheng** [comment]
![image](https://user-images.githubusercontent.com/20603896/87680946-9e2ad480-c7b0-11ea-9aa9-1403112954c9.png)

**Comment by cjfff** [comment]
了解

**Comment by cjfff** [comment]
fixed it and the Repositories is move to [this](https://github.com/FEMessage/dockerize-cli) 😄  thanks for feedback
